apiVersion: v1
kind: Service
metadata:
  name: user-service-green-preview
  namespace: production

spec:
  selector:
    app: user-service
    slot: green

  ports:
    - port: 8000
      targetPort: 8000

  type: ClusterIP